# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Contract + unit tests for tools/device_code_proof.py.

The classifier is exercised against synthetic PTX so the whole suite runs without a GPU, without
a build tree, and (mostly) without the CUDA toolkit. The few end-to-end cases that do invoke
`nvcc` are skipped when it is absent, and never need a GPU.
"""

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent.parent
TOOL = REPO / "tools" / "device_code_proof.py"

needs_nvcc = pytest.mark.skipif(
    shutil.which("nvcc") is None,
    reason="the CUDA toolkit is not installed (no GPU needed)",
)


def run(*args, timeout=300):
    return subprocess.run(
        [sys.executable, str(TOOL), *args],
        cwd=str(REPO),
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def _module():
    spec = importlib.util.spec_from_file_location("device_code_proof", TOOL)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def ptx(*entries, target="sm_86"):
    head = "//\n// Generated by NVIDIA NVVM Compiler\n//\n\n.version 9.3\n.target %s\n.address_size 64\n"
    return head % target + "\n" + "\n".join(entries) + "\n"


def entry(name, params, body):
    decls = ",\n".join(
        "\t.param %s %s_param_%d" % (p, name, i) for i, p in enumerate(params)
    )
    return (
        ".visible .entry %s(\n%s\n)\n{\n\t.reg .b32 \t%%r<4>;\n\t.reg .b64 \t%%rd<3>;\n\n%s\n\tret;\n\n}"
        % (
            name,
            decls,
            "\n".join("\t" + b for b in body),
        )
    )


# The provenance case: an unused `int` parameter is deleted, so the mangled name loses one `i`
# and every later parameter slot renumbers. Nothing else moves.
BASE_PTX = ptx(
    entry(
        "_Z3fooPfii",
        [".u64", ".u32", ".u32"],
        [
            "ld.param.u64 \t%rd1, [_Z3fooPfii_param_0];",
            "ld.param.u32 \t%r1, [_Z3fooPfii_param_2];",
            "add.s32 \t%r2, %r1, 1;",
            "st.global.u32 \t[%rd1], %r2;",
        ],
    )
)
HEAD_PTX = ptx(
    entry(
        "_Z3fooPfi",
        [".u64", ".u32"],
        [
            "ld.param.u64 \t%rd1, [_Z3fooPfi_param_0];",
            "ld.param.u32 \t%r1, [_Z3fooPfi_param_1];",
            "add.s32 \t%r2, %r1, 1;",
            "st.global.u32 \t[%rd1], %r2;",
        ],
    )
)


def only_pair(m, base_text, head_text):
    _, base_units = m.parse_ptx(base_text)
    _, head_units = m.parse_ptx(head_text)
    pairs, extra_base, extra_head = m.match_units(base_units, head_units, {})
    assert not extra_base and not extra_head, "expected every unit to pair"
    assert len(pairs) == 1
    return m.classify(*pairs[0])


# --------------------------------------------------------------------------- parser
def test_parse_ptx_reads_header_entries_and_data():
    m = _module()
    text = ptx(
        ".global .align 4 .b8 table[4] = {1, 2, 3, 4};", BASE_PTX.split("\n\n", 2)[2]
    )
    header, units = m.parse_ptx(text)
    assert header == {"version": "9.3", "target": "sm_86", "address_size": "64"}
    kinds = {u.kind: u.name for u in units}
    assert kinds["data"] == "table"
    assert kinds["entry"] == "_Z3fooPfii"


def test_forward_declarations_are_not_units():
    m = _module()
    _, units = m.parse_ptx(
        ptx(".visible .func  (.param .b32 r) helper(.param .b32 a);")
    )
    assert units == []


# --------------------------------------------------------------------------- classification
def test_unchanged_ptx_is_identical():
    m = _module()
    assert only_pair(m, BASE_PTX, BASE_PTX)[0] == m.IDENTICAL


def test_removed_unused_parameter_is_signature_only():
    """The exact shape of the provenance run: mangled name shorter, parameter slots renumbered,
    not one instruction different. It must not read as identical and must not read as a rewrite.
    """
    m = _module()
    klass, detail = only_pair(m, BASE_PTX, HEAD_PTX)
    assert klass == m.SIGNATURE_ONLY
    assert "mangled name changed" in detail
    assert "params 3 -> 2" in detail


def test_signature_only_is_never_a_silent_pass():
    m = _module()
    results = [{"units": [{"class": m.SIGNATURE_ONLY}], "counts": {}}]
    assert m.verdict_of(results) == m.NEEDS_JUDGEMENT
    assert m.EXIT[m.NEEDS_JUDGEMENT] != 0


def test_changed_instruction_is_a_real_delta():
    m = _module()
    changed = BASE_PTX.replace("add.s32 \t%r2, %r1, 1;", "add.s32 \t%r2, %r1, 2;")
    klass, detail = only_pair(m, BASE_PTX, changed)
    assert klass == m.CHANGED
    assert "changed line(s)" in detail
    assert m.EXIT[m.verdict_of([{"units": [{"class": klass}], "counts": {}}])] == 1


def test_changed_register_pressure_is_a_real_delta():
    """A different register budget means the compiler did different work, even when every
    instruction reads the same."""
    m = _module()
    assert only_pair(m, BASE_PTX, BASE_PTX.replace("%r<4>", "%r<9>"))[0] == m.CHANGED


def test_reordered_parameters_are_not_waved_through():
    """Two parameters swapped is *not* provable-safe, and looks a lot like a dropped parameter.
    It has to leave the tool as something a human must read, never as identical."""
    m = _module()
    swapped = HEAD_PTX.replace("_param_0];", "_TMP];").replace(
        "_param_1];", "_param_0];"
    )
    swapped = swapped.replace("_TMP];", "_param_1];")
    klass, detail = only_pair(m, HEAD_PTX, swapped)
    assert klass == m.SIGNATURE_ONLY
    assert "reorder, not a renumbering" in detail
    assert m.verdict_of([{"units": [{"class": klass}]}]) == m.NEEDS_JUDGEMENT


def test_added_and_removed_entries_are_real_deltas():
    m = _module()
    two = BASE_PTX + "\n" + entry("_Z3barv", [], ["mov.u32 \t%r1, %tid.x;"])
    _, base_units = m.parse_ptx(BASE_PTX)
    _, head_units = m.parse_ptx(two)
    pairs, extra_base, extra_head = m.match_units(base_units, head_units, {})
    assert len(pairs) == 1 and not extra_base
    assert [u.name for u in extra_head] == ["_Z3barv"]
    assert (
        m.verdict_of([{"units": [{"class": m.ADDED}], "counts": {}}])
        == m.DEVICE_CODE_CHANGED
    )
    assert (
        m.verdict_of([{"units": [{"class": m.REMOVED}], "counts": {}}])
        == m.DEVICE_CODE_CHANGED
    )


def test_changed_module_data_is_a_real_delta():
    m = _module()
    before = ptx(".global .align 4 .b8 table[4] = {1, 2, 3, 4};")
    after = ptx(".global .align 4 .b8 table[4] = {1, 2, 3, 5};")
    assert only_pair(m, before, after)[0] == m.CHANGED


# --------------------------------------------------------------------------- normalization
def test_label_renumbering_is_not_a_delta():
    """`$L__BB7_1` carries the function's position in the module, so adding any unrelated kernel
    renumbers the labels of every other one."""
    m = _module()
    before = ptx(entry("_Z1kv", [], ["@%p1 bra \t$L__BB0_2;", "$L__BB0_2:"]))
    after = ptx(entry("_Z1kv", [], ["@%p1 bra \t$L__BB9_2;", "$L__BB9_2:"]))
    assert only_pair(m, before, after)[0] == m.IDENTICAL


def test_debug_line_directives_are_ignored():
    """`.loc` is source line numbers, not device code; a refactor moves lines by construction."""
    m = _module()
    after = BASE_PTX.replace("\tadd.s32", "\t.loc 1 42 3\n\tadd.s32")
    assert only_pair(m, BASE_PTX, after)[0] == m.IDENTICAL


def test_whitespace_is_not_a_delta():
    m = _module()
    assert only_pair(m, BASE_PTX, BASE_PTX.replace("\t", "    "))[0] == m.IDENTICAL


def test_anonymous_namespace_discriminator_is_blanked():
    """nvcc stamps a fresh discriminator on every compilation, so without this the same kernel
    never matches itself and the tool is not reproducible."""
    m = _module()
    a = "_ZN47_GLOBAL__N__392c4f3d_14_OpAdjustHue_cu_57bdee5815AdjustHuePlanarEv"
    b = "_ZN47_GLOBAL__N__453318f0_14_OpAdjustHue_cu_57bdee5815AdjustHuePlanarEv"
    assert m.canonical_symbol(a) == m.canonical_symbol(b)
    # the Itanium length prefix counts those characters, so the length must survive
    assert len(m.canonical_symbol(a)) == len(a)


def test_base_name_drops_the_argument_list_only():
    m = _module()
    demangled = "void k<nvcv::cuda::TensorWrapT<unsigned char, int>>(int2, int, Consts)"
    assert (
        m._base_name(demangled) == "void k<nvcv::cuda::TensorWrapT<unsigned char, int>>"
    )


def test_short_elides_the_middle_not_the_tail():
    """Sibling instantiations of one kernel template differ in their last template argument."""
    m = _module()
    a = m._short("void k<" + "x" * 90 + ", 1>")
    b = m._short("void k<" + "x" * 90 + ", 4>")
    assert a != b and a.startswith("void k<")


# --------------------------------------------------------------------------- flags & paths
def _entry(command):
    return {"command": command, "directory": "/build", "file": "/repo/src/a.cu"}


def test_compile_flags_strip_what_ptx_cannot_take():
    m = _module()
    tu = REPO / "src/cvcuda/priv/OpAdvCvtColor.cu"
    command = (
        "nvcc -forward-unknown-to-host-compiler -DNVCV_DEBUG=1 -I/repo/src -isystem /cuda/include "
        "--generate-code=arch=compute_80,code=[sm_80] -Xfatbin=--compress-all --compress-mode=size "
        "-O3 -std=c++17 -MD -MT obj.o -MF obj.o.d -x cu -c %s -o obj.o" % tu
    )
    argv, _source, label = m.compile_flags(_entry(command), tu, Path("/build"))
    assert "compile_commands.json" in label
    assert not [
        a
        for a in argv
        if a.startswith(("--generate-code", "-Xfatbin", "--compress-mode"))
    ]
    assert (
        "-c" not in argv
        and "-o" not in argv
        and "-MF" not in argv
        and "obj.o" not in argv
    )
    assert (
        str(tu) not in argv
    ), "the source positional is re-added against the scratch tree"
    # real build flags are kept verbatim: a hand-rolled set drifts and drifted flags change codegen
    assert "-O3" in argv and "-std=c++17" in argv and "-DNVCV_DEBUG=1" in argv


def test_compile_flags_keep_isystem_pairs_exactly_once():
    """Regression: emitting the pair *and* falling through duplicated the path, which nvcc reads
    as a second input file ('a single input file is required for a non-link phase')."""
    m = _module()
    tu = REPO / "src/cvcuda/priv/OpAdvCvtColor.cu"
    argv, _s, _l = m.compile_flags(
        _entry("nvcc -isystem /cuda/include -x cu -c %s -o obj.o" % tu),
        tu,
        Path("/build"),
    )
    assert argv.count("/cuda/include") == 1


def test_compile_flags_fall_back_without_a_compile_database():
    m = _module()
    tu = REPO / "src/cvcuda/priv/OpAdvCvtColor.cu"
    argv, source, label = m.compile_flags(None, tu, Path("/build"))
    assert "synthesized" in label
    assert source == str(tu)
    assert any(a.startswith("-I") and a.endswith("src") for a in argv)
    assert "-std=c++17" in argv


def test_redirect_repoints_repo_paths_but_not_build_paths():
    m = _module()
    argv = [
        "-I%s/src/cvcuda/include" % REPO,
        "-I%s/build-rel/src/cvcuda/include" % REPO,
        "-O3",
    ]
    out = m.redirect(argv, ["src"], Path("/scratch"))
    assert out[0] == "-I/scratch/src/cvcuda/include"
    assert (
        out[1] == argv[1]
    ), "generated headers are not versioned; there is no per-ref copy"
    assert out[2] == "-O3"


def test_moved_tops_skips_the_build_directory():
    m = _module()
    build = REPO / "build-rel"
    argv = [
        "-I%s/src" % REPO,
        "-I%s/src/cvcuda/include" % build,
        "-I/usr/local/cuda/include",
    ]
    assert m.moved_tops(argv, [REPO / "src/cvcuda/priv/OpAdvCvtColor.cu"], build) == [
        "src"
    ]


def test_include_dirs_understands_both_spellings():
    m = _module()
    assert m.include_dirs(["-I/a", "-I", "/b", "-isystem", "/c", "-isystem/d"]) == [
        "/a",
        "/b",
        "/c",
        "/d",
    ]


def test_stub_headers_render_every_placeholder(tmp_path):
    m = _module()
    written = m.stub_generated_headers(tmp_path)
    assert "cvcuda/VersionDef.h" in written and "nvcv/VersionDef.h" in written
    for name in written:
        text = (tmp_path / name).read_text()
        # Doxygen tags (@file, @defgroup) survive on purpose; the CMake placeholders must not.
        for placeholder in ("@LIBPREFIX@",) + tuple("@%s@" % k for k in m.STUB_VALUES):
            assert placeholder not in text, "%s still has %s" % (name, placeholder)


# --------------------------------------------------------------------------- report contract
def test_verdict_ranking_prefers_the_worst_finding():
    m = _module()
    mixed = [
        {
            "units": [
                {"class": m.IDENTICAL},
                {"class": m.SIGNATURE_ONLY},
                {"class": m.CHANGED},
            ]
        }
    ]
    assert m.verdict_of(mixed) == m.DEVICE_CODE_CHANGED
    assert m.verdict_of([{"units": [{"class": m.IDENTICAL}]}]) == m.MATCH
    assert m.verdict_of([{"units": [], "error": "boom"}]) == m.FAILED


def test_exit_codes_are_non_zero_for_anything_but_a_match():
    m = _module()
    assert m.EXIT[m.MATCH] == 0
    assert all(
        m.EXIT[v] != 0 for v in (m.NEEDS_JUDGEMENT, m.DEVICE_CODE_CHANGED, m.FAILED)
    )


def test_every_report_states_what_it_does_not_prove():
    """The limits travel with the output, not just with the guidance doc: a pasted report has to
    carry its own caveats."""
    m = _module()
    payload = {
        "operator": "Foo",
        "base": "HEAD",
        "head": "<working tree>",
        "arches": ["sm_86"],
        "flag_source": "synthesized",
        "skipped": [],
        "results": [],
        "verdict": m.MATCH,
        "stage": "ptx",
        "limits": m.limits("ptx"),
    }
    report = m.render_md(payload)
    assert "does not prove" in report.lower()
    assert "host-side" in report and "SASS" in report
    assert "Not a substitute" in report


def test_changed_detail_pipe_is_escaped_in_table():
    """A 'changed' detail string contains ` | ` separators from classify(); without escaping
    those split the Markdown table row into extra columns and break the rendered report.
    """
    m = _module()
    # Construct a payload whose detail contains " | " as classify() would produce.
    payload = {
        "operator": "Foo",
        "base": "HEAD",
        "head": "<working tree>",
        "arches": ["sm_86"],
        "flag_source": "synthesized",
        "skipped": [],
        "results": [
            {
                "tu": "src/cvcuda/priv/OpFoo.cu",
                "arch": "sm_86",
                "units": [
                    {
                        "name": "_Z3foov",
                        "mangled": "_Z3foov",
                        "kind": "entry",
                        "class": m.CHANGED,
                        "detail": "3 changed line(s), +1 instructions; e.g. +add.s32 | -sub.s32",
                    }
                ],
                "counts": {m.CHANGED: 1},
            }
        ],
        "verdict": m.DEVICE_CODE_CHANGED,
        "reverted": [],
        "stage": "ptx",
        "limits": m.limits("ptx"),
        "signature_change_accepted": False,
    }
    report = m.render_md(payload)
    # Each data row must have exactly 3 columns (two separating pipes inside the row)
    for line in report.splitlines():
        if line.startswith("| `") and "changed" in line:
            inner = line[1:-1]  # strip leading and trailing |
            # The raw " | " from the detail must be escaped so it reads as \| not a column break
            assert r"\|" in inner, "pipe in detail not escaped: %r" % line
            break
    else:
        pytest.fail("no changed row found in rendered report")


# --------------------------------------------------------------------------- CLI contract
def test_no_target_is_a_usage_error():
    result = run()
    assert result.returncode == 2
    assert "Traceback" not in result.stderr


def test_invalid_format_is_a_usage_error():
    assert run("Flip", "--format", "bogus").returncode == 2


def test_file_outside_repository_is_rejected(tmp_path):
    """--file paths that resolve outside the repository are rejected before any compilation.

    An out-of-repo file is compiled from disk on both sides and would always report MATCH
    for something that was never versioned at --base — a silent false positive.
    """
    out_of_repo = tmp_path / "fake.cu"
    out_of_repo.write_text(".visible .entry _Z4fake() { ret; }\n")
    result = run("--file", str(out_of_repo))
    assert result.returncode == 2
    assert "repository" in result.stderr
    assert "Traceback" not in result.stderr


def test_revert_outside_repository_is_rejected(tmp_path):
    """--revert paths that resolve outside REPO are rejected before overlay() can write them.

    An absolute path in ``reverted`` discards ``dest`` in pathlib's ``dest / name``, letting
    overlay() write to arbitrary locations on the host filesystem.
    """
    out_of_repo = tmp_path / "evil.cu"
    out_of_repo.write_text("// evil\n")
    result = run(
        "--file", "src/cvcuda/priv/OpAdvCvtColor.cu", "--revert", str(out_of_repo)
    )
    assert result.returncode == 2
    assert "repository" in result.stderr
    assert "Traceback" not in result.stderr


@needs_nvcc
def test_host_only_sources_are_refused_rather_than_silently_passed():
    result = run("--file", "src/cvcuda/priv/OpFlip.cpp")
    assert result.returncode == 2
    assert "host-only" in result.stderr
    assert "Traceback" not in result.stderr


@needs_nvcc
def test_unknown_operator_degrades_gracefully():
    result = run("NotARealOperator")
    assert result.returncode == 2
    assert "Traceback" not in result.stderr


@needs_nvcc
def test_end_to_end_unchanged_tree_matches():
    result = run(
        "--file",
        "src/cvcuda/priv/OpAdvCvtColor.cu",
        "--arch",
        "sm_86",
        "--build-dir",
        "does-not-exist",
        "--format",
        "json",
    )
    assert result.returncode == 0, result.stderr
    payload = json.loads(result.stdout)
    assert payload["verdict"] == "MATCH"
    assert payload["flag_source"].startswith("synthesized")
    counts = payload["results"][0]["counts"]
    assert counts.get("identical", 0) > 0 and set(counts) == {"identical"}


@needs_nvcc
def test_end_to_end_report_is_deterministic():
    args = (
        "--file",
        "src/cvcuda/priv/OpAdvCvtColor.cu",
        "--arch",
        "sm_86",
        "--build-dir",
        "does-not-exist",
        "--format",
        "json",
    )
    assert run(*args).stdout == run(*args).stdout


@needs_nvcc
def test_a_real_shared_header_refactor_proves_bit_exact():
    """End-to-end against a merged refactor that moved ~300 lines of one operator into a shared
    header. Every kernel must come out identical; if this ever fails, the normalization is
    hiding or inventing a difference."""
    commit = "4b47e766de29e9bbd548ed92b60c43ccee315212"
    if subprocess.run(["git", "cat-file", "-e", commit], cwd=str(REPO)).returncode != 0:
        pytest.skip("%s is not in this clone" % commit)
    result = run(
        "AdjustHue",
        "--base",
        commit + "^",
        "--head",
        commit,
        "--arch",
        "sm_86",
        "--format",
        "json",
    )
    assert result.returncode == 0, result.stdout + result.stderr
    payload = json.loads(result.stdout)
    assert payload["verdict"] == "MATCH"
    assert payload["results"][0]["counts"]["identical"] >= 10
