# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

include_guard(GLOBAL)

# This must run before CUDA is enabled. Afterwards CMake populates
# CMAKE_CUDA_ARCHITECTURES even when neither the cache nor CUDAARCHS supplied it.
macro(cvcuda_detect_cuda_architecture_source)
    if(DEFINED CMAKE_CUDA_ARCHITECTURES)
        if(DEFINED CVCUDA_GENERATED_CUDA_ARCHITECTURES
           AND "${CMAKE_CUDA_ARCHITECTURES}" STREQUAL "${CVCUDA_GENERATED_CUDA_ARCHITECTURES}")
            set(_CVCUDA_CUDA_ARCHITECTURES_SOURCE "GENERATED")
        else()
            set(_CVCUDA_CUDA_ARCHITECTURES_SOURCE "EXPLICIT_CACHE")
        endif()
    elseif(NOT "$ENV{CUDAARCHS}" STREQUAL "")
        set(_CVCUDA_CUDA_ARCHITECTURES_SOURCE "ENVIRONMENT")
    else()
        set(_CVCUDA_CUDA_ARCHITECTURES_SOURCE "GENERATED")
    endif()
endmacro()

function(cvcuda_configure_cuda_architecture_policy)
    if(NOT DEFINED _CVCUDA_CUDA_ARCHITECTURES_SOURCE)
        message(FATAL_ERROR "cvcuda_detect_cuda_architecture_source() must run before enabling CUDA")
    endif()

    set(_CVCUDA_CANONICAL_COMPACT_X86_ARCHITECTURES)
    if(ARCH_X86_64)
        if(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "11.8")
            list(APPEND _CVCUDA_CANONICAL_COMPACT_X86_ARCHITECTURES
                80-real # Ampere - ga100/Tesla; binary-compatible baseline for SM8.x
                90-real # Hopper - gh100/Tesla
            )
        endif()
        if(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "12.8")
            list(APPEND _CVCUDA_CANONICAL_COMPACT_X86_ARCHITECTURES
                100-real # Blackwell B200, B300
                120-real # RTX Pro 6000, RTX 50**
            )
        endif()
        list(APPEND _CVCUDA_CANONICAL_COMPACT_X86_ARCHITECTURES 75-real)
    endif()

    if(_CVCUDA_CUDA_ARCHITECTURES_SOURCE STREQUAL "GENERATED")
        set(_CVCUDA_CUDA_ARCHITECTURES)

        if(ARCH_X86_64)
            set(_CVCUDA_CUDA_ARCHITECTURES
                "${_CVCUDA_CANONICAL_COMPACT_X86_ARCHITECTURES}")
        elseif(ARCH_AARCH64)
            if(CVCUDA_AARCH64_JETSON)
                # Jetson Orin platforms only.
                list(APPEND _CVCUDA_CUDA_ARCHITECTURES
                    86-real # IGX Orin + Ampere RTX A6000
                    87-real # Jetson AGX Orin - ga10b,ga10c/Tegra
                    89-real # IGX Orin + Ada RTX 6000
                )
            else()
                # SBSA server platforms (default).
                list(APPEND _CVCUDA_CUDA_ARCHITECTURES
                    80-real # Ampere - ga100/Tesla
                    86-real # Ampere - ga10x
                    89-real # Ada - ad10x
                )
                if(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "11.8")
                    list(APPEND _CVCUDA_CUDA_ARCHITECTURES
                        90-real # Grace Hopper - gh100/Tesla
                    )
                endif()
                if(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "12.8")
                    list(APPEND _CVCUDA_CUDA_ARCHITECTURES
                        100-real # Blackwell GB200, GB300
                    )
                endif()
                if(CMAKE_CUDA_COMPILER_VERSION VERSION_GREATER_EQUAL "13.0")
                    list(APPEND _CVCUDA_CUDA_ARCHITECTURES
                        110-real # Thor
                        121-real # DGX Spark
                    )
                endif()
            endif()
        endif()

        if(ARCH_AARCH64 AND NOT CVCUDA_AARCH64_JETSON)
            # Native Turing code avoids requiring a newer driver to JIT build-toolkit PTX.
            list(APPEND _CVCUDA_CUDA_ARCHITECTURES 75-real)
        endif()

        set(CMAKE_CUDA_ARCHITECTURES "${_CVCUDA_CUDA_ARCHITECTURES}" CACHE STRING
            "CUDA architectures to build for" FORCE)
        set(CVCUDA_GENERATED_CUDA_ARCHITECTURES "${_CVCUDA_CUDA_ARCHITECTURES}" CACHE INTERNAL
            "CUDA architectures generated by CV-CUDA" FORCE)
    elseif(_CVCUDA_CUDA_ARCHITECTURES_SOURCE STREQUAL "ENVIRONMENT")
        # CUDAARCHS is a complete CMake architecture list, not a prefix for our defaults.
        set(CMAKE_CUDA_ARCHITECTURES "$ENV{CUDAARCHS}" CACHE STRING
            "CUDA architectures to build for" FORCE)
        unset(CVCUDA_GENERATED_CUDA_ARCHITECTURES CACHE)
    elseif(_CVCUDA_CUDA_ARCHITECTURES_SOURCE STREQUAL "EXPLICIT_CACHE")
        # Preserve every explicit cache spelling, including OFF, FALSE, and 0.
        unset(CVCUDA_GENERATED_CUDA_ARCHITECTURES CACHE)
    else()
        message(FATAL_ERROR
            "Unknown CUDA architecture source: ${_CVCUDA_CUDA_ARCHITECTURES_SOURCE}")
    endif()

    set(CVCUDA_TARGETED_SM8X_CUBINS "AUTO" CACHE STRING
        "Build supplemental native SM86/SM89 operator cubins (AUTO, ON, or OFF)")
    set_property(CACHE CVCUDA_TARGETED_SM8X_CUBINS PROPERTY STRINGS AUTO ON OFF)
    string(TOUPPER "${CVCUDA_TARGETED_SM8X_CUBINS}" _CVCUDA_TARGETED_SM8X_CUBINS)
    if(NOT _CVCUDA_TARGETED_SM8X_CUBINS MATCHES "^(AUTO|ON|OFF)$")
        message(FATAL_ERROR
            "CVCUDA_TARGETED_SM8X_CUBINS must be AUTO, ON, or OFF; got '${CVCUDA_TARGETED_SM8X_CUBINS}'")
    endif()
    set(CVCUDA_TARGETED_SM8X_CUBINS "${_CVCUDA_TARGETED_SM8X_CUBINS}" CACHE STRING
        "Build supplemental native SM86/SM89 operator cubins (AUTO, ON, or OFF)" FORCE)
    set_property(CACHE CVCUDA_TARGETED_SM8X_CUBINS PROPERTY STRINGS AUTO ON OFF)

    set(_CVCUDA_EFFECTIVE_ARCHITECTURES ${CMAKE_CUDA_ARCHITECTURES})
    set(_CVCUDA_CANONICAL_ARCHITECTURES ${_CVCUDA_CANONICAL_COMPACT_X86_ARCHITECTURES})
    list(REMOVE_DUPLICATES _CVCUDA_EFFECTIVE_ARCHITECTURES)
    list(REMOVE_DUPLICATES _CVCUDA_CANONICAL_ARCHITECTURES)
    list(SORT _CVCUDA_EFFECTIVE_ARCHITECTURES)
    list(SORT _CVCUDA_CANONICAL_ARCHITECTURES)
    if(ARCH_X86_64
       AND "${_CVCUDA_EFFECTIVE_ARCHITECTURES}" STREQUAL "${_CVCUDA_CANONICAL_ARCHITECTURES}")
        set(_CVCUDA_USES_CANONICAL_COMPACT_X86_ARCHITECTURES ON)
    else()
        set(_CVCUDA_USES_CANONICAL_COMPACT_X86_ARCHITECTURES OFF)
    endif()

    if(_CVCUDA_TARGETED_SM8X_CUBINS STREQUAL "ON"
       OR (_CVCUDA_TARGETED_SM8X_CUBINS STREQUAL "AUTO"
           AND _CVCUDA_USES_CANONICAL_COMPACT_X86_ARCHITECTURES))
        set(CVCUDA_TARGETED_SM8X_CUBINS_ACTIVE ON CACHE INTERNAL
            "Whether supplemental native SM86/SM89 operator cubins are active" FORCE)
    else()
        set(CVCUDA_TARGETED_SM8X_CUBINS_ACTIVE OFF CACHE INTERNAL
            "Whether supplemental native SM86/SM89 operator cubins are active" FORCE)
    endif()

    # set(... CACHE) does not replace a same-named normal variable under CMP0126.
    set(CMAKE_CUDA_ARCHITECTURES "${CMAKE_CUDA_ARCHITECTURES}" PARENT_SCOPE)
    set(CVCUDA_TARGETED_SM8X_CUBINS_ACTIVE "${CVCUDA_TARGETED_SM8X_CUBINS_ACTIVE}" PARENT_SCOPE)
endfunction()

# Appends SASS-only native SM86/SM89 code generation to selected CUDA sources.
# Recompiling the owning source with extra -gencode entries keeps its current
# host symbols and kernel implementations intact, while the CUDA runtime picks
# the exact native image on matching devices. SELECTED_SOURCES_VAR names the
# caller's already-filtered source list, so CV_CUDA_SRC_PATERN builds never
# compile supplemental code for an operator they did not select.
function(cvcuda_add_targeted_cuda_architectures_to_sources)
    set(_CVCUDA_OPTIONS)
    set(_CVCUDA_ONE_VALUE_ARGS SELECTED_SOURCES_VAR)
    set(_CVCUDA_MULTI_VALUE_ARGS ARCHITECTURES SOURCES)
    cmake_parse_arguments(PARSE_ARGV 0 CVCUDA_TARGETED
        "${_CVCUDA_OPTIONS}" "${_CVCUDA_ONE_VALUE_ARGS}" "${_CVCUDA_MULTI_VALUE_ARGS}")

    if(CVCUDA_TARGETED_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR
            "cvcuda_add_targeted_cuda_architectures_to_sources() got unknown arguments: "
            "${CVCUDA_TARGETED_UNPARSED_ARGUMENTS}")
    endif()
    foreach(_CVCUDA_REQUIRED_ARG IN ITEMS ARCHITECTURES SOURCES SELECTED_SOURCES_VAR)
        if(NOT CVCUDA_TARGETED_${_CVCUDA_REQUIRED_ARG})
            message(FATAL_ERROR
                "cvcuda_add_targeted_cuda_architectures_to_sources() requires ${_CVCUDA_REQUIRED_ARG}")
        endif()
    endforeach()
    if(NOT DEFINED ${CVCUDA_TARGETED_SELECTED_SOURCES_VAR})
        message(FATAL_ERROR
            "cvcuda_add_targeted_cuda_architectures_to_sources() SELECTED_SOURCES_VAR names an undefined variable: "
            "${CVCUDA_TARGETED_SELECTED_SOURCES_VAR}")
    endif()

    set(_CVCUDA_TARGETED_ARCHITECTURES)
    foreach(_CVCUDA_ARCH IN LISTS CVCUDA_TARGETED_ARCHITECTURES)
        if(NOT "${_CVCUDA_ARCH}" MATCHES "^(86|89)(-real)?$")
            message(FATAL_ERROR
                "Targeted CUDA architecture must be 86, 86-real, 89, or 89-real; got '${_CVCUDA_ARCH}'")
        endif()
        string(REGEX REPLACE "-real$" "" _CVCUDA_ARCH "${_CVCUDA_ARCH}")
        list(APPEND _CVCUDA_TARGETED_ARCHITECTURES "${_CVCUDA_ARCH}")
    endforeach()
    list(REMOVE_DUPLICATES _CVCUDA_TARGETED_ARCHITECTURES)

    # Resolve CMake's special architecture tokens before deciding which native
    # images already apply globally. A bare numeric architecture produces both
    # SASS and PTX, while a -real entry produces SASS. Only -virtual entries
    # still need a supplemental native image.
    set(_CVCUDA_RESOLVED_GLOBAL_ARCHITECTURES)
    foreach(_CVCUDA_GLOBAL_ARCH IN LISTS CMAKE_CUDA_ARCHITECTURES)
        if(_CVCUDA_GLOBAL_ARCH STREQUAL "all")
            list(APPEND _CVCUDA_RESOLVED_GLOBAL_ARCHITECTURES ${CMAKE_CUDA_ARCHITECTURES_ALL})
        elseif(_CVCUDA_GLOBAL_ARCH STREQUAL "all-major")
            list(APPEND _CVCUDA_RESOLVED_GLOBAL_ARCHITECTURES ${CMAKE_CUDA_ARCHITECTURES_ALL_MAJOR})
        elseif(_CVCUDA_GLOBAL_ARCH STREQUAL "native")
            list(APPEND _CVCUDA_RESOLVED_GLOBAL_ARCHITECTURES ${CMAKE_CUDA_ARCHITECTURES_NATIVE})
        else()
            list(APPEND _CVCUDA_RESOLVED_GLOBAL_ARCHITECTURES "${_CVCUDA_GLOBAL_ARCH}")
        endif()
    endforeach()
    foreach(_CVCUDA_GLOBAL_ARCH IN LISTS _CVCUDA_RESOLVED_GLOBAL_ARCHITECTURES)
        if(_CVCUDA_GLOBAL_ARCH MATCHES "^([0-9]+)(-real)?$")
            list(REMOVE_ITEM _CVCUDA_TARGETED_ARCHITECTURES "${CMAKE_MATCH_1}")
        endif()
    endforeach()

    if(NOT CVCUDA_TARGETED_SM8X_CUBINS_ACTIVE OR NOT _CVCUDA_TARGETED_ARCHITECTURES)
        return()
    endif()

    foreach(_CVCUDA_SOURCE IN LISTS CVCUDA_TARGETED_SOURCES)
        list(FIND ${CVCUDA_TARGETED_SELECTED_SOURCES_VAR} "${_CVCUDA_SOURCE}" _CVCUDA_SOURCE_INDEX)
        if(_CVCUDA_SOURCE_INDEX EQUAL -1)
            continue()
        endif()

        get_property(_CVCUDA_SOURCE_OPTIONS SOURCE "${_CVCUDA_SOURCE}" PROPERTY COMPILE_OPTIONS)
        foreach(_CVCUDA_ARCH IN LISTS _CVCUDA_TARGETED_ARCHITECTURES)
            set(_CVCUDA_GENCODE_OPTION
                "$<$<COMPILE_LANGUAGE:CUDA>:--generate-code=arch=compute_${_CVCUDA_ARCH},code=sm_${_CVCUDA_ARCH}>")
            list(FIND _CVCUDA_SOURCE_OPTIONS "${_CVCUDA_GENCODE_OPTION}" _CVCUDA_OPTION_INDEX)
            if(_CVCUDA_OPTION_INDEX EQUAL -1)
                set_property(SOURCE "${_CVCUDA_SOURCE}" APPEND PROPERTY
                    COMPILE_OPTIONS "${_CVCUDA_GENCODE_OPTION}")
                list(APPEND _CVCUDA_SOURCE_OPTIONS "${_CVCUDA_GENCODE_OPTION}")
            endif()
        endforeach()
    endforeach()
endfunction()
